/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
struct sensor_data {
	int32_t temperature;
    uint8_t status;
    int16_t pressure;
};

struct  __attribute__((packed)) sensor_data_packed {
    int32_t temperature;
    uint8_t status;
    int16_t pressure;
};

void modify_sensor1_data(struct sensor_data *s1){
	s1->status = 0x3;
//	 80002d0: 2303       movs	r3, #3
//	 80002d2: 7103       strb	r3, [r0, #4]
	s1->pressure = 1225;
//	 80002d4: f44f 63c9  mov.w r3, #1225
//	 80002d8: 8143       strh	r3, [r0, #6]
}

void modify_sensor2_data(struct sensor_data_packed *s2){
	s2->status = 0x3;
//	 80002dc: 2303       movs	r3, #3
//	 80002de: 7103       strb	r3, [r0, #4]
	s2->pressure = 1225;
//	 80002e0:  f44f 63c9  mov.w r3, #1225
//	 80002e2: 7103       strb	r3, [r0, #5]
//	 80002e0: 0b1b       lsrs	r3, r3, #8
//	 80002e2: 7143       strb	r3, [r0, #5]
}


int main(void) {
    struct sensor_data sensor1 = {25, 0x01, 1013};
    struct sensor_data_packed sensor2 = {.temperature = 25,
    									 .pressure = 1012,
										 .status = 0x01 };

    printf("sensor1: Temp = %ld, Press = %d, Status = 0x%X sizeof %d bytes\n",
           sensor1.temperature,
           sensor1.pressure,
           sensor1.status,
		   sizeof(sensor1));

    printf("sensor2: Temp = %ld, Press = %d, Status = 0x%X sizeof %d bytes \n",
    		sensor2.temperature,
			sensor2.pressure,
			sensor2.status,
		    sizeof(sensor2));
    modify_sensor1_data(&sensor1);
    modify_sensor2_data(&sensor2);
	for(;;);
}
