/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
/***
 * // Convert a bit-band memory address and bit number to its alias address
#define BITBAND_SRAM(addr, bit) \
    ((volatile uint32_t*)(0x22000000 + (((uint32_t)(addr) - 0x20000000) * 32) + ((bit) * 4)))

#define BITBAND_PERIPH(addr, bit) \
    ((volatile uint32_t*)(0x42000000 + (((uint32_t)(addr) - 0x40000000) * 32) + ((bit) * 4)))

// Example usage:
volatile uint32_t* led_bit = BITBAND_PERIPH(&GPIOA->ODR, 5);
*led_bit = 1;  // Turn LED on
 */
// Define direct pointers to frequently used bits
#define LED_GREEN    ((volatile uint32_t*)(0x42400294))  // GPIOA->ODR bit 5
#define BUTTON_USER  ((volatile uint32_t*)(0x42408090))  // GPIOC->IDR bit 4

void toggle_led(void) {
    *LED_GREEN = !(*LED_GREEN);  // Atomic toggle
}

uint32_t read_button(void) {
    return *BUTTON_USER;  // Atomic read
}


int main(void)
{
	// Calculate bit-band address for GPIOA->ODR bit 5
	// GPIOA->ODR is at 0x40020014
	// Offset from peripheral base: 0x20014
	// Bit position: 5

	// Bit-band alias address:
	// 0x42000000 + (0x20014 * 32) + (5 * 4)
	// = 0x42000000 + 0x400280 + 0x14
	// = 0x42400294

	// Create a pointer to the bit
	volatile uint32_t* pin5_bb = (volatile uint32_t*)(0x42400294);

	// Atomic operations
	*pin5_bb = 1;  // Set pin 5 high (atomic)
	*pin5_bb = 0;  // Set pin 5 low (atomic)
	for(;;);
}
