/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>



/******************Simple Function ******************/
int add_and_multiply(int a, int b, int c) {
    int sum = a + b;
    int result = sum * c;
    return result;
}


/*******************Function with Stack-Based Parameters******************/
int calculate(int a, int b, int c, int d, int e, int f) {
    return a + b + c + d + e + f;
}


/*******************Function with Local Variables on Stack******************/
int process_data(int input){
    int buffer[4] = {0, 1, 2, 3};
    int sum = 0;

    for (int i = 0; i < 4; i++) {
        sum += input * buffer[i];
    }

    return sum;
}


/*******************Function Call Within Function******************/
int inner_function(int a, int b) {
    return a * b;
}

int outer_function(int x, int y) {
    int result = inner_function(x, y);
    return result + 10;
}
/*******************Function Call Within Function******************/



int main(void)
{
    int res = add_and_multiply(1, 2, 3);
    int res2 = calculate(res, 1, 2, 3, 4 ,5);
    int res3 = process_data(res2);

    res = outer_function(res3, res2);
	for(;;);
}
