/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int assembly_mul(int input){
	uint32_t result;

	__asm volatile(
	    "MUL %0, %1, %1\n\t"  // Square the input value
	    : "=r" (result)       // Output: register only
	    : "r" (input)         // Input: register only
	);
	return result;
}

void swap(uint32_t ptr1, uint32_t ptr2) {
    uint32_t temp1, temp2;

    __asm volatile(
        "LDR %0, [%2]\n\t"    // Load from ptr1
        "LDR %1, [%3]\n\t"    // Load from ptr2
        "STR %1, [%2]\n\t"    // Store ptr2's value to ptr1
        "STR %0, [%3]\n\t"    // Store sum to ptr2
        : "=&r" (temp1), "=&r" (temp2)  // Early clobber outputs
        : "r" (ptr1), "r" (ptr2)        // Input pointers
        : "memory"                      // Memory is modified
    );
}

__attribute__((naked))uint32_t read_sp(void) {
    uint32_t sp_value;
    __asm volatile("MOV %0, sp" : "=r"(sp_value));
    return sp_value;  // Returns in R0 automatically
}

int main(void)
{
    uint32_t sp_read = read_sp();
    sp_read++;
	for(;;);
}
