/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

//Address offset: 0x30 RCC_AHB1ENR
//RRC base address 0x4002 3800
//#define RCC_AHB1ENR ((0x40023800) + (0x30))
//
//// GPIOD base addr 0x4002 0C00
//#define GPIOD_base_addr  (0x40020C00)
//#define GPIOD_MODER (GPIOD_base_addr + (0x0))
//// GPIOD mode register 0x00
//
////GPIO D data output register offset GPIO port output data register (GPIOx_ODR) 0x14
//#define GPIOD_ODR (GPIOD_base_addr + (0x14))
//#define GPIO_OUTPUT_MODE 0x1

const uint32_t RCC_AHB1ENR      = ((0x40023800) + (0x30));
const uint32_t GPIOD_BASE_ADDR  = (0x40020C00);
const uint32_t GPIOD_MODER      = (GPIOD_BASE_ADDR + (0x0));
const uint32_t GPIOD_ODR        = (GPIOD_BASE_ADDR + (0x14));
const uint32_t GPIO_OUTPUT_MODE = 0x1;

int main(void)
{

	uint32_t *p_clk_ctrl_reg = (uint32_t *)(RCC_AHB1ENR);
	uint32_t *p_gpioD_mode_reg = (uint32_t *)(GPIOD_MODER);
	volatile uint32_t * const p_gpioD_out_reg = (volatile uint32_t *)(GPIOD_ODR);

//	get the RRC value
	*p_clk_ctrl_reg |= (0x1 << 3);
//	clear p_gpioD_mode_reg
	*p_gpioD_mode_reg &= ~(0x3 << 24);
//	set the p_gpioD_mode_reg
	*p_gpioD_mode_reg |= (0x1 << 24);
//	set the pin output
	*p_gpioD_out_reg |= (0x1 << 12);

    // Simple blink loop
    while(1) {
        // Toggle LED
        *p_gpioD_out_reg ^= (0x1 << 12);

        // Delay (volatile counter prevents optimization)
        for(volatile uint32_t i = 0; i < 5000; i++);
    }
}

/**
 Register definitions as const variables instead of macros
	const uint32_t RCC_AHB1ENR      = ((0x40023800) + (0x30));
	const uint32_t GPIOD_BASE_ADDR  = (0x40020C00);
	const uint32_t GPIOD_MODER      = (GPIOD_BASE_ADDR + (0x0));
	const uint32_t GPIOD_ODR        = (GPIOD_BASE_ADDR + (0x14));
	const uint32_t GPIO_OUTPUT_MODE = 0x1;
    volatile uint32_t * const p_clk_ctrl_reg = (volatile uint32_t *)(RCC_AHB1ENR);
    volatile uint32_t * const p_gpioD_mode_reg = (volatile uint32_t *)(GPIOD_MODER);
    volatile uint32_t * const p_gpioD_out_reg = (volatile uint32_t *)(GPIOD_ODR);
 */
