/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

// Function to calculate CRC on a buffer
uint32_t calculate_crc(uint8_t *data, uint32_t length) {
    volatile uint32_t *CRC_DR = (volatile uint32_t *)(0x40023000);
    volatile uint32_t *CRC_CR = (volatile uint32_t *)(0x40023008);

    // Reset CRC calculation
    *CRC_CR = 0x01;

    // Feed data
    for (uint32_t i = 0; i < length; i++) {
        *CRC_DR = data[i];
    }

    // Return result
    return *CRC_DR;
}

int main(void)
{
	uint8_t a[2];
	int ret = calculate_crc(a, 2);
	printf("ret %d", ret);
	for(;;);
}


